# Generated by Django 4.2.1 on 2024-05-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.CharField(choices=[('Mobiles', 'Mobiles'), ('Electronic', 'Electronic'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Book', 'Book'), ('EGIFT Card', 'EGIFT Card'), ('Market', 'Market'), ('watch', 'watch'), ('shoes', 'shoes'), ('clothes', 'clothes'), ('other', 'other')], max_length=200, null=True)),
                ('num_views', models.IntegerField(blank=True, null=True)),
                ('error_codes', models.TextField(blank=True, null=True)),
                ('redundant_codes', models.TextField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjapp.customer')),
            ],
        ),
    ]
