# Generated by Django 4.2.1 on 2024-05-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0002_customerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='num_views',
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='price',
        ),
    ]
