# Generated by Django 4.2.1 on 2024-05-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0003_remove_customerproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
