# Generated by Django 4.2.1 on 2024-06-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0004_customerproduct_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='get_invoice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
