# Generated by Django 4.2.1 on 2024-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0005_customerproduct_get_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='who',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
