# Generated by Django 4.2.1 on 2024-06-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0006_customerproduct_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
