# Generated by Django 4.2.1 on 2024-06-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0007_product_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_us_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='all_codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
