# Generated by Django 4.2.1 on 2024-06-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0008_customerproduct_amazon_us_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='Apple_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
