# Generated by Django 4.2.1 on 2024-06-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0009_customerproduct_apple_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('cards', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prjapp.customerproduct')),
            ],
        ),
    ]
