# Generated by Django 4.2.1 on 2024-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0011_customerproduct_amazon_de_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_100',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_de_50',
            field=models.TextField(blank=True, null=True),
        ),
    ]
