# Generated by Django 4.2.1 on 2024-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0012_customerproduct_amazon_de_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_100',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Amazon_uk_50',
            field=models.TextField(blank=True, null=True),
        ),
    ]
