# Generated by Django 4.2.1 on 2024-07-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0014_cards_search_delete_cards_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='num_codes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
