# Generated by Django 4.2.1 on 2024-07-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0015_customerproduct_num_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_100',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Razer_50',
            field=models.TextField(blank=True, null=True),
        ),
    ]
