# Generated by Django 4.2.1 on 2024-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjapp', '0016_customerproduct_razer_10_customerproduct_razer_100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='Apple_40',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='Apple_60',
            field=models.TextField(blank=True, null=True),
        ),
    ]
